Blog-Django-MySQL/MetalFighter/urls.py
'''
    本项目下的url与path信息。

'''

from django.urls import path
from django.conf.urls import url
from . import views

app_name = "MetalFighter"

urlpatterns = [
    path('login/', views.login, name='login'),
    path('quit/', views.logout, name='quit'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('queryInfo/', views.query_passage, name='query'),
    path('charge/', views.recharge, name='charge'),
    path('<int:question_id>/passageDetail/', views.show_passage, name='pass_detail'),
    path('authorWork/', views.own_passage, name='authorWork'),
    path('pushBlog/', views.write_blog, name='writeBlog'),
    path('', views.index, name="index"),
    path('platform/', views.platform, name="platform"),
    path('py30', views.pay_30, name="p30"),
    path('py90', views.pay_90, name="p90"),
    path('py180', views.pay_180, name="p180"),
]

Blog-Django-MySQL/Team4/urls.py
from django.contrib import admin
from django.urls import path, include
# import xadmin
from django.conf.urls import url
# xadmin.autodiscover()
# from xadmin.plugins import xversion
# xversion.register_models()


urlpatterns = [
    path('', include('MetalFighter.urls')),
    path('MetalFighter/', include('MetalFighter.urls')),
    path('admin/', admin.site.urls),
    # url(r'^adain', admin.site.urls),
    # path('admin/', admin.site.urls),
]

Blog-Django-MySQL/MetalFighter/models.py
from django.db import models


# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=200, verbose_name='测试名')
    age = models.IntegerField(default=0, verbose_name='测试数')
    email = models.EmailField(verbose_name='测试邮箱')

    def __str__(self):
        return str(self.name) + "\t" + str(self.age) + "\t" + str(self.email)


class User(models.Model):
    nickname = models.CharField(max_length=20, blank=False, unique=True, verbose_name='昵称')
    birth = models.DateField(verbose_name='出生日期')
    phone = models.CharField(max_length=15, verbose_name='电话号码')
    email = models.EmailField(verbose_name='电子邮箱')
    status = models.BooleanField(verbose_name='账户状态')
    info = models.TextField(blank=True, verbose_name='个人说明')
    user_name = models.CharField(max_length=12, verbose_name='用户名')
    password = models.CharField(max_length=20, verbose_name='密码')
    role = models.BooleanField(verbose_name='VIP状态')
    balance = models.BigIntegerField(default=0, blank=False, verbose_name='VIP剩余时间')


class Passage(models.Model):
    title = models.CharField(max_length=40, blank=False, verbose_name='标题')
    author = models.CharField(max_length=20, verbose_name='作者')
    subscribe = models.CharField(max_length=60, blank=True, verbose_name='描述')
    time = models.DateField(auto_now=True, verbose_name='发表时间')
    pic_no = models.IntegerField(default=1, verbose_name='图片编号')
    context = models.TextField(verbose_name='文章内容')

Blog-Django-MySQL/MetalFighter/forms.py
'''
    Store the forms
    Check if the figures are valid
'''

from django import forms


class BlogForm(forms.Form):
    title = forms.CharField()
    author = forms.CharField()
    subscribe = forms.CharField(required=False)
    pic_no = forms.IntegerField()
    context = forms.CharField()


class UserForm(forms.Form):
    loginUser = forms.CharField(max_length=100)
    loginPwd = forms.CharField(max_length=100)


class RegisterForm(forms.Form):
    nickname = forms.CharField(max_length=20)
    birth = forms.DateField()
    phone = forms.CharField()
    email = forms.EmailField()
    status = forms.BooleanField()
    info = forms.CharField()
    user_name = forms.CharField(max_length=12)
    password = forms.CharField(max_length=20)


class Recharge(forms.Form):
    charge = forms.CharField()

Blog-Django-MySQL/MetalFighter/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.core import serializers
from django.db.models import Q
from . import models, forms
from .forms import UserForm, RegisterForm
import json


# Create your views here.

def index(request):
    return HttpResponseRedirect('/MetalFighter/queryInfo')


def platform(request):
    tid = request.POST['test']
    target = models.Contact.objects.get(id=tid)
    print(target)
    tarList = []
    tarList.append(target)
    info = {
        'answerPhone': tarList
    }
    return render(request, 'MetalFighter/SQLSHOW.html', info)


def login(request):
    # 如果是登录功能
    if request.method == 'POST':
        # uf = UserForm(request)
        # 根据值确认表单是否有错
        # if uf.is_valid():
        #     username = uf.cleaned_data['loginUser']
        #     password = uf.cleaned_data['loginPwd']
        username = request.POST['loginUser']
        password = request.POST['loginPwd']
        # return HttpResponse('GSS')
        user = models.User.objects.filter(user_name=username, password=password)
        users = serializers.serialize('json', user)
        if len(users) != 2:
            # 10 将users 传递到前端请求
            request.session['username'] = users
            request.session['has'] = 1
            # 11 设置该session的有效时长
            request.session.set_expiry(6000)
            return HttpResponseRedirect('/MetalFighter/queryInfo')
        else:
            return render(request, 'MetalFighter/login.html', {

            })
    else:
        return render(request, 'MetalFighter/login.html', {

        })


def logout(request):
    try:
        del request.session['username']
        request.session['has'] = 0
    except KeyError:
        pass
    return HttpResponseRedirect('/MetalFighter/queryInfo')


def recharge(request):
    if request.method == 'POST':
        # user = models.User.objects.filter(user_name='ppp', password='ppp')
        # users = serializers.serialize('json', user)
        # request.session['username'] = users
        ss = request.session['username']
        if ss is not None and ss != '':
            sss = ss.strip('[')
            sss = sss.strip(']')
            str = json.loads(sss)
            # print(str['fields']['nickname'])
            charge = int(request.POST['charge'])
            print(charge)
            print(str['fields']['balance'] + charge)
            models.User.objects.filter(user_name=str['fields']['user_name']).update(
                balance=(str['fields']['balance'] + charge), role=True)
            return HttpResponseRedirect('/MetalFighter/queryInfo')
        else:
            return render(request, 'MetalFighter/login.html', {

            })
    else:
        print('傻逼')
        return render(request, 'MetalFighter/member.html', {
            'username':'none'
        })


def register(request):
    # 如果是注册功能
    if request.method == 'POST':
        nickname = request.POST['nickname']
        birth = request.POST['birth']
        phone = request.POST['phone']
        email = request.POST['email']
        info = request.POST['info']
        user_name = request.POST['user_name']
        password = request.POST['password']
        print(user_name, password)
        user = models.User.objects.filter(user_name=user_name)
        user1 = models.User.objects.filter(nickname=nickname)
        user2 = models.User.objects.filter(phone=phone)
        print(len(user))
        if len(user) == 0 and len(user1) == 0 and len(user2) == 0:
            # 9 重定向到index.html
            create = models.User.objects.create(nickname=nickname, birth=birth, phone=phone, email=email, status=0,
                                                info=info, user_name=user_name, password=password, role=0, balance=0)
            print(type(create), create)
            return HttpResponseRedirect('/MetalFighter/queryInfo')
        else:
            return render(request, 'MetalFighter/register.html', {

            })
    else:
        return render(request, 'MetalFighter/register.html', {

        })


def show_passage(request, question_id):
    pid = question_id
    targetPassage = models.Passage.objects.get(id=pid)
    print(targetPassage.context)
    try:
        ss = request.session['username']
        sss = ss.strip('[')
        sss = sss.strip(']')
        str = json.loads(sss)
        username = str['fields']['user_name']
    except KeyError:
        username = "none"

    backInfo = {
        'title': targetPassage.title,
        'author': targetPassage.author,
        'time': targetPassage.time,
        'subscribe': targetPassage.subscribe,
        'context': targetPassage.context,
        'username': username
    }
    return render(request, 'MetalFighter/article.html', backInfo)


def is_vip(nickname):
    user = models.User.objects.get(nickname=nickname)
    if user is not None and user.role is True:
        return True
    else:
        return False


def sort_cmp(passage):
    if is_vip(passage.author):
        return -1
    else:
        return 1


def query_passage(request):
    try:
        ss = request.session['username']
        sss = ss.strip('[')
        sss = sss.strip(']')
        str = json.loads(sss)
        username = str['fields']['user_name']
    except KeyError:
        username = "none"
    if request.method == 'POST':
        queryInfo = request.POST['queryInfo']
        passageList = models.Passage.objects.filter(Q(title__icontains=queryInfo) | Q(author__icontains=queryInfo) |
                                                    Q(subscribe__icontains=queryInfo) | Q(context__icontains=queryInfo))
        passageList = list(passageList)
        passageList.sort(key=lambda passage: sort_cmp(passage))
        backInfo = {
            'passages': passageList,
            'username': username,
        }
        # return render(request, 'MetalFighter/234.html', backInfo)
        return HttpResponse('Good')
    else:
        passageList = models.Passage.objects.all()
        passageList = list(passageList)
        passageList.sort(key=lambda passage: sort_cmp(passage))
        backInfo = {
            'passages': passageList,

            'username': username,
        }
        return render(request, 'MetalFighter/main.html', backInfo)


def own_passage(request):
    # user = models.User.objects.filter(user_name='ppp', password='ppp')
    # users = serializers.serialize('json', user)
    # request.session['username'] = users
    try:
        ss = request.session['username']
        sss = ss.strip('[')
        sss = sss.strip(']')
        str = json.loads(sss)
        author = str['fields']['nickname']
        username = str['fields']['user_name']
    except KeyError:
        username = "none"
        author = ''
    if author is not '':
        passageList = models.Passage.objects.filter(author=author)
        passageList = list(passageList)
        for pas in passageList:
            print(pas.context)
        backInfo = {
            'passages': passageList,
            'username': username,
        }
        return render(request, 'MetalFighter/myblog.html', backInfo)
    else:
        return HttpResponseRedirect('/MetalFighter/queryInfo')


def write_blog(request):
    if request.method == 'POST':
        # user = models.User.objects.filter(user_name='ppp', password='ppp')
        # users = serializers.serialize('json', user)
        # request.session['username'] = users
        try:
            ss = request.session['username']
            sss = ss.strip('[')
            sss = sss.strip(']')
            str = json.loads(sss)
            author = str['fields']['nickname']
            print (str['fields']['nickname'])
            if author is not '':
                blog = forms.BlogForm(request.POST)
                if request.POST['context'] is not '':
                    subscr = ''
                    contex = request.POST['context']
                    if len(contex) < 30:
                        subscr = contex
                    else:
                        subscr = contex[0:30]
                models.Passage.objects.create(title=request.POST['title'], author=author,
                                              subscribe=subscr,
                                              pic_no=2, context=request.POST['context'])
                return HttpResponseRedirect('/MetalFighter/authorWork')
        except KeyError:
            return HttpResponseRedirect('/MetalFighter/queryInfo')
    else:
        return render(request, 'MetalFighter/write.html', {
        })



def pay_30(request):
    try:
        ss = request.session['username']
        sss = ss.strip('[')
        sss = sss.strip(']')
        str = json.loads(sss)
    except KeyError:
        return HttpResponseRedirect('/MetalFighter/queryInfo')

    return render(request, 'MetalFighter/pay30.html', {

    })


def pay_90(request):
    try:
        ss = request.session['username']
        sss = ss.strip('[')
        sss = sss.strip(']')
        str = json.loads(sss)
    except KeyError:
        return HttpResponseRedirect('/MetalFighter/queryInfo')

    return render(request, 'MetalFighter/pay70.html', {

    })


def pay_180(request):
    try:
        ss = request.session['username']
        sss = ss.strip('[')
        sss = sss.strip(']')
        str = json.loads(sss)
    except KeyError:
        return HttpResponseRedirect('/MetalFighter/queryInfo')

    return render(request, 'MetalFighter/pay200.html', {

    })

Blog-Django-MySQL/templates/MetalFighter/12121.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for answer in answerPhone %}
<p>{{ answer }}</p>
{% endfor %}
<form action="{% url 'MetalFighter:platform' %}" method="post">
    <input type="text" name="test" value="4">
    {% csrf_token %}
    <input type="submit" value="send">
</form>
<a href="http://127.0.0.1:8000/MetalFighter/platform"/>LINK
</body>
</html>

Blog-Django-MySQL/templates/MetalFighter/23232.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for answer in answerPhone %}
    <p>{{ answer.name }}</p>
    <p>{{ answer.email }}</p>
{% endfor %}
</body>
</html>

Blog-Django-MySQL/templates/MetalFighter/pay200.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>pay200</title>
    <link rel="icon" href="img/favicon.ico">
    <!-- CSS FILES -->
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.6/css/uikit.min.css">
    <style>
        .uk-container-small {
            max-width: 46rem;
        }

        .whole {
            min-height: 650px;
        }
    </style>
</head>
<body>
<div class="uk-offcanvas-content">
    <!--HEADER-->
    <header style="background-color: rgba(214, 211, 211, 0.747); border-bottom: 1px solid #f2f2f2;"
            data-uk-sticky="show-on-up: true; animation: uk-animation-slide-top">
        <div class="uk-container">
            <nav id="navbar" data-uk-navbar="mode: click;" style="height :75px;">
                <div class="uk-navbar-left">
                    <ul class="uk-navbar-nav">
                        <li>
                            <a href="#" data-uk-icon="icon:user"></a>
                            <div class="uk-navbar-dropdown uk-navbar-dropdown-bottom-left">
                                <ul class="uk-nav uk-navbar-dropdown-nav">
                                    <li class="uk-nav-header uk-text-small uk-text-primary">YOUR ACCOUNT</li>
                                    <li><a href="#"><span data-uk-icon="icon: heart"></span> 我的收藏</a></li>
                                    <li><a href="#"><span data-uk-icon="icon: settings"></span> 修改个人信息</a></li>
                                    <li class="uk-nav-divider"></li>
                                    <li><a href="#"><span data-uk-icon="icon: sign-out"></span> 注销</a></li>

                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="uk-navbar-right">
                    <ul class="uk-navbar-nav uk-visible@m">
                        <li class="uk-active"><a href="/MetalFighter/queryInfo">地图广场</a></li>
                        <li><a href="/MetalFighter/authorWork">我的博客</a></li>
                        <li><a href="/MetalFighter/pushBlog">写博客</a></li>
                        <li><a href="/MetalFighter/charge">购买会员</a></li>
                        <li><a href="/MetalFighter/register">注册</a></li>
                    </ul>
                    <div class="uk-navbar-item">
                        <a class="uk-navbar-toggle uk-hidden@s" data-uk-toggle data-uk-navbar-toggle-icon
                           href="#offcanvas-nav"></a>
                        {% if  username != "none" %}
{#                            <a href="/MetalFighter/login" class="uk-button uk-button-secondary uk-visible@m"><span#}
{#                                    data-uk-icon="sign-in"></span>登出</a>#}
                             <form action="{% url 'MetalFighter:logout' %}" method="post">
                                {% csrf_token %}
                                <button class="uk-button uk-button-secondary uk-visible@m" data-uk-icon="sign-out" type="submit">登出</button>
                             </form>
                        {% else %}
                            <a href="/MetalFighter/login" class="uk-button uk-button-secondary uk-visible@m"><span
                                    data-uk-icon="sign-in"></span>登录</a>
                        {% endif %}
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <!--/HEADER-->
    <!--主体-->
    <div class="whole">
        <!--AUTHOR-->
        <section class="uk-section uk-section-muted uk-padding-remove-bottom">
            <div class="uk-container uk-container-medium">
                <header class="uk-text-center">
                    <h1 class="uk-heading-primary">支付页面</h1>
                    <p class="uk-width-4-5 uk-margin-auto">
                        扫描下方二维码进行付款
                    </p>
                </header>
                <div class="uk-grid uk-grid-medium uk-child-width-3-5@m uk-margin-auto uk-grid-match"
                     data-uk-scrollspy="cls: uk-animation-slide-bottom-small; target: > div > .uk-card; delay: 200"
                     data-uk-grid style="max-width: 500px; margin-bottom: 20px">
                    <!-- price -->
                    <div>
                        <div class="uk-card uk-card-default uk-card-hover uk-flex uk-flex-column">
                            <div class="uk-card-header uk-text-center">
                                <h4 class="uk-text-bold" style="font-size: 30px">180天</h4>
                            </div>
                            <div class="uk-card-body uk-flex-1">
                                <img src="{% static "img/200.jpg" %}"/>
                            </div>
                            <div class="uk-card-footer">
                                <form method="post" action="{% url 'MetalFighter:charge' %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="charge" value="180">
                                    <button type="submit"
                                            class="uk-button uk-button-primary uk-button-primary uk-button-medium uk-width-1-1">
                                        支付成功
                                    </button>
                                </form>
                                <a href="/MetalFighter/charge" class="uk-button uk-button-success"
                                   style="max-width: 200px;margin-bottom: 10px">返回</a>
                            </div>
                        </div>
                    </div>
                    <!-- /price -->
                </div>
            </div>
        </section>
    </div>
    <!--/主体-->
    <!-- footer -->
    <div class="uk-flex-bottom">
        <footer class="uk-section uk-section-small"
                style="margin-bottom: 10px; background-color: rgba(223, 223, 223, 0.747);max-height: 40px;">
            <div class="uk-container">
                <p class="uk-text-small uk-text-center">2018 - 幺蛾子 | Built with <a href="http://getuikit.com"
                                                                                   title="Visit UIkit 3 site"
                                                                                   target="_blank" data-uk-tooltip><span
                        data-uk-icon="uikit"></span></a></p>
            </div>
        </footer>
    </div>
    <!-- /footer -->
</div>
<!-- JS FILES -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.6/js/uikit.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.6/js/uikit-icons.min.js"></script>
</body>
</html>

Blog-Django-MySQL/templates/MetalFighter/pay30.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>pay30</title>
    <link rel="icon" href="img/favicon.ico">
    <!-- CSS FILES -->
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.6/css/uikit.min.css">
    <style>
        .uk-container-small {
            max-width: 46rem;
        }

        .whole {
            min-height: 650px;
        }
    </style>
</head>
<body>
<div class="uk-offcanvas-content">
    <!--HEADER-->
    <header style="background-color: rgba(214, 211, 211, 0.747); border-bottom: 1px solid #f2f2f2;"
            data-uk-sticky="show-on-up: true; animation: uk-animation-slide-top">
        <div class="uk-container">
            <nav id="navbar" data-uk-navbar="mode: click;" style="height :75px;">
                <div class="uk-navbar-left">
                    <ul class="uk-navbar-nav">
                        <li>
                            <a href="#" data-uk-icon="icon:user"></a>
                            <div class="uk-navbar-dropdown uk-navbar-dropdown-bottom-left">
                                <ul class="uk-nav uk-navbar-dropdown-nav">
                                    <li class="uk-nav-header uk-text-small uk-text-primary">YOUR ACCOUNT</li>
                                    <li><a href="#"><span data-uk-icon="icon: heart"></span> 我的收藏</a></li>
                                    <li><a href="#"><span data-uk-icon="icon: settings"></span> 修改个人信息</a></li>
                                    <li class="uk-nav-divider"></li>
                                    <li><a href="#"><span data-uk-icon="icon: sign-out"></span> 注销</a></li>

                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="uk-navbar-right">
                    <ul class="uk-navbar-nav uk-visible@m">
                        <li class="uk-active"><a href="/MetalFighter/queryInfo">地图广场</a></li>
                        <li><a href="/MetalFighter/authorWork">我的博客</a></li>
                        <li><a href="/MetalFighter/pushBlog">写博客</a></li>
                        <li><a href="/MetalFighter/charge">购买会员</a></li>
                        <li><a href="/MetalFighter/register">注册</a></li>
                    </ul>
                    <div class="uk-navbar-item">
                        <a class="uk-navbar-toggle uk-hidden@s" data-uk-toggle data-uk-navbar-toggle-icon
                           href="#offcanvas-nav"></a>
                        {% if  username != "none" %}
{#                            <a href="/MetalFighter/login" class="uk-button uk-button-secondary uk-visible@m"><span#}
{#                                    data-uk-icon="sign-in"></span>登出</a>#}
                             <form action="{% url 'MetalFighter:logout' %}" method="post">
                                {% csrf_token %}
                                <button class="uk-button uk-button-secondary uk-visible@m" data-uk-icon="sign-out" type="submit">登出</button>
                             </form>
                        {% else %}
                            <a href="/MetalFighter/login" class="uk-button uk-button-secondary uk-visible@m"><span
                                    data-uk-icon="sign-in"></span>登录</a>
                        {% endif %}
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <!--/HEADER-->
    <!--主体-->
    <div class="whole">
        <!--AUTHOR-->
        <section class="uk-section uk-section-muted uk-padding-remove-bottom">
            <div class="uk-container uk-container-medium">
                <header class="uk-text-center">
                    <h1 class="uk-heading-primary">支付页面</h1>
                    <p class="uk-width-4-5 uk-margin-auto">
                        扫描下方二维码进行付款
                    </p>
                </header>
                <div class="uk-grid uk-grid-medium uk-child-width-3-5@m uk-margin-auto uk-grid-match"
                     data-uk-scrollspy="cls: uk-animation-slide-bottom-small; target: > div > .uk-card; delay: 200"
                     data-uk-grid style="max-width: 500px; margin-bottom: 20px">
                    <!-- price -->
                    <div>
                        <div class="uk-card uk-card-default uk-card-hover uk-flex uk-flex-column">
                            <div class="uk-card-header uk-text-center">
                                <h4 class="uk-text-bold" style="font-size: 30px">30天</h4>
                            </div>
                            <div class="uk-card-body uk-flex-1">
                                <img src="{% static "img/27.jpg" %}"/>
                            </div>
                            <div class="uk-card-footer">
                                <form method="post" action="{% url 'MetalFighter:charge' %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="charge" value="30">
                                    <button type="submit"
                                            class="uk-button uk-button-primary uk-button-primary uk-button-medium uk-width-1-1">
                                        支付成功
                                    </button>
                                </form>
                                <a href="/MetalFighter/charge" class="uk-button uk-button-success"
                                   style="max-width: 200px;margin-bottom: 10px">返回</a>
                            </div>
                        </div>
                    </div>
                    <!-- /price -->
                </div>
            </div>
        </section>
    </div>
    <!--/主体-->
    <!-- footer -->
    <div class="uk-flex-bottom">
        <footer class="uk-section uk-section-small"
                style="margin-bottom: 10px; background-color: rgba(223, 223, 223, 0.747);max-height: 40px;">
            <div class="uk-container">
                <p class="uk-text-small uk-text-center">2018 - 幺蛾子 | Built with <a href="http://getuikit.com"
                                                                                   title="Visit UIkit 3 site"
                                                                                   target="_blank" data-uk-tooltip><span
                        data-uk-icon="uikit"></span></a></p>
            </div>
        </footer>
    </div>
    <!-- /footer -->
</div>
<!-- JS FILES -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.6/js/uikit.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.6/js/uikit-icons.min.js"></script>
</body>
</html>

Blog-Django-MySQL/templates/MetalFighter/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


</body>
</html>

Blog-Django-MySQL/templates/MetalFighter/test2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    <form action="{% url 'MetalFighter:query' %}" method="post">
        <input type="text" name="queryInfo" value="tim">
        {% csrf_token %}
        <input type="submit" value="send">
    </form>
</div>
<div>
    <form action="{% url 'MetalFighter:pass_detail' %}" method="post">
        <input type="text" name="pid" value="3">
        {% csrf_token %}
        <input type="submit" value="send">
    </form>
</div>
<div>
    <form action="{% url 'MetalFighter:authorWork' %}" method="post">
        <input type="text" name="author" value="ppp">
        {% csrf_token %}
        <input type="submit" value="send">
    </form>
</div>
<div>
    <form action="{% url 'MetalFighter:writeBlog' %}" method="post">
        <input type="text" name="title" value="tenka">
        <input type="text" name="author" value="ppp">
        <input type="text" name="subscribe" value="ieofkcnv">
        <input type="text" name="pic_no" value="3">
        <input type="text" name="context" value="456yujuqdr4tyjuki78l6dfgej654w">
        {% csrf_token %}
        <input type="submit" value="send">
    </form>
</div>
</body>
</html>